# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a0dd131bfe5ec1096573c3fd70d2bfe768ab30ff3aeaacda19dcf5c81ff1a40279a9b01968cd24c0b6bc3bd821c99c525f4ee02e2d6f455ee40a42c221f150b

test:
  secret_key_base: d0bde28b07cd192d54894851b300f321bb14d2694d3660b8e5fa3632938385834208a805fe912b3a4b242fba43e34295917f40c006bf363b6aedf2848aebe0b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
